language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t keaneb17/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true keaneb17/docker-react npm run test